dbt_juice_dev_source:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: sales_oltp
      schema: source
      threads: 4
