dbt_med_dev:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DWH_DATABASE', 'sales_dwh') }}"
      schema: staging
      threads: 4
