dbt_med_dev:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5432
      dbname: sales_oltp
      schema: raw
      threads: 4